import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

Qdf = pd.read_csv('SA_Params_logL_Baisman_Flow_SQL_max1000_20samps.csv')

#Get rank of all replicates for each metric
logLranks = np.argsort(Qdf['logL'])[::-1]
SSEdBCranks = np.argsort(Qdf['SSEdBC'])
SSEdranks = np.argsort(Qdf['SSEd'])
SSEwranks = np.argsort(Qdf['SSEw'])
SSEmranks = np.argsort(Qdf['SSEm'])
SSEaranks = np.argsort(Qdf['SSEa'])
NSEdBCranks = np.argsort(Qdf['NSEdBC'])
NSEdranks = np.argsort(Qdf['NSEd'])
NSEwranks = np.argsort(Qdf['NSEw'])
NSEmranks = np.argsort(Qdf['NSEm'])
NSEaranks = np.argsort(Qdf['NSEa'])
LNSEdranks = np.argsort(Qdf['LNSEd'])
LNSEwranks = np.argsort(Qdf['LNSEw'])
LNSEmranks = np.argsort(Qdf['LNSEm'])
LNSEaranks = np.argsort(Qdf['LNSEa'])
pBiasranks = np.argsort(Qdf['pBias'])

#Spearman Correlation
plt.scatter(logLranks,SSEdBCranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEdBCranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by SSEdBC (Flow)')
plt.savefig('Flow_Ranks_logL_v_SSEdBC.png')
plt.clf()

plt.scatter(logLranks,SSEdranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEdranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by SSEd (Flow)')
plt.savefig('Flow_Ranks_logL_v_SSEd.png')
plt.clf()

plt.scatter(logLranks,SSEwranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEwranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by SSEw (Flow)')
plt.savefig('Flow_Ranks_logL_v_SSEw.png')
plt.clf()

plt.scatter(logLranks,SSEmranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEmranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by SSEm (Flow)')
plt.savefig('Flow_Ranks_logL_v_SSEm.png')
plt.clf()

plt.scatter(logLranks,SSEaranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEaranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by SSEa (Flow)')
plt.savefig('Flow_Ranks_logL_v_SSEa.png')
plt.clf()

plt.scatter(logLranks,NSEdBCranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,NSEdBCranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by NSEdBC (Flow)')
plt.savefig('Flow_Ranks_logL_v_NSEdBC.png')
plt.clf()

plt.scatter(logLranks,NSEdranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,NSEdranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by NSEd (Flow)')
plt.savefig('Flow_Ranks_logL_v_NSEd.png')
plt.clf()

plt.scatter(logLranks,NSEwranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,NSEwranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by NSEw (Flow)')
plt.savefig('Flow_Ranks_logL_v_NSEw.png')
plt.clf()

plt.scatter(logLranks,NSEmranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,NSEmranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by NSEm (Flow)')
plt.savefig('Flow_Ranks_logL_v_NSEm.png')
plt.clf()

plt.scatter(logLranks,NSEaranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,NSEaranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by NSEa (Flow)')
plt.savefig('Flow_Ranks_logL_v_NSEa.png')
plt.clf()

plt.scatter(logLranks,LNSEdranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,LNSEdranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by LNSEd (Flow)')
plt.savefig('Flow_Ranks_logL_v_LNSEd.png')
plt.clf()

plt.scatter(logLranks,LNSEwranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,LNSEwranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by LNSEw (Flow)')
plt.savefig('Flow_Ranks_logL_v_LNSEw.png')
plt.clf()

plt.scatter(logLranks,LNSEmranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,LNSEmranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by LNSEm (Flow)')
plt.savefig('Flow_Ranks_logL_v_LNSEm.png')
plt.clf()

plt.scatter(logLranks,LNSEaranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,LNSEaranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by LNSEa (Flow)')
plt.savefig('Flow_Ranks_logL_v_LNSEa.png')
plt.clf()

plt.scatter(logLranks,pBiasranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,pBiasranks)[0,1]))
plt.xlabel('Ranks by logL (Flow)')
plt.ylabel('Ranks by pBias (Flow)')
plt.savefig('Flow_Ranks_logL_v_pBias.png')
plt.clf()

#Pearson Correlation
plt.scatter(-Qdf['logL'],Qdf['SSEdBC'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['SSEdBC'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['SSEdBC'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('SSEdBC (Flow)')
plt.savefig('Flow_logL_v_SSEdBC.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['SSEd'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['SSEd'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['SSEd'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('SSEd (Flow)')
plt.savefig('Flow_logL_v_SSEd.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['SSEw'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['SSEw'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['SSEw'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('SSEw (Flow)')
plt.savefig('Flow_logL_v_SSEw.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['SSEm'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['SSEm'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['SSEm'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('SSEm (Flow)')
plt.savefig('Flow_logL_v_SSEm.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['SSEa'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['SSEa'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['SSEa'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('SSEa (Flow)')
plt.savefig('Flow_logL_v_SSEa.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['NSEdBC'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['NSEdBC'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['NSEdBC'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('NSEdBC (Flow)')
plt.savefig('Flow_logL_v_NSEdBC.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['NSEd'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['NSEd'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['NSEd'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('NSEd (Flow)')
plt.savefig('Flow_logL_v_NSEd.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['NSEw'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['NSEw'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['NSEw'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('NSEw (Flow)')
plt.savefig('Flow_logL_v_NSEw.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['NSEm'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['NSEm'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['NSEm'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('NSEm (Flow)')
plt.savefig('Flow_logL_v_NSEm.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['NSEa'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['NSEa'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['NSEa'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('NSEa (Flow)')
plt.savefig('Flow_logL_v_NSEa.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['LNSEd'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['LNSEd'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['LNSEd'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('LNSEd (Flow)')
plt.savefig('Flow_logL_v_LNSEd.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['LNSEw'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['LNSEw'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['LNSEw'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('LNSEw (Flow)')
plt.savefig('Flow_logL_v_LNSEw.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['LNSEm'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['LNSEm'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['LNSEm'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('LNSEm (Flow)')
plt.savefig('Flow_logL_v_LNSEm.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['LNSEa'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['LNSEa'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['LNSEa'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('LNSEa (Flow)')
plt.savefig('Flow_logL_v_LNSEa.png')
plt.clf()

plt.scatter(-Qdf['logL'],Qdf['pBias'])
plt.scatter(-Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['logL'],Qdf.iloc[np.where(Qdf['success'] == False)[0],:]['pBias'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-Qdf['logL'],Qdf['pBias'])[0,1]))
plt.xlabel('-logL (Flow)')
plt.ylabel('pBias (Flow)')
plt.savefig('Flow_logL_v_pBias.png')
plt.clf()

TNdf = pd.read_csv('SA_Params_logL_Baisman_TN_SQL_max1000_20samps.csv')

logLranks = np.argsort(TNdf['logL'])[::-1]
SSEranks = np.argsort(TNdf['SSE'])
plt.scatter(logLranks,SSEranks)
plt.title('Spearman Correlation= ' + str(np.corrcoef(logLranks,SSEranks)[0,1]))
plt.xlabel('Ranks by logL (TN)')
plt.ylabel('Ranks by SSE (TN)')
plt.savefig('TN_Ranks_logL_v_SSE_20samps.png')
plt.clf()

plt.scatter(-TNdf['logL'],TNdf['SSE'])
plt.scatter(-TNdf.iloc[np.where(TNdf['success'] == False)[0],:]['logL'],TNdf.iloc[np.where(TNdf['success'] == False)[0],:]['SSE'], c='red')
plt.title('Pearson Correlation= ' + str(np.corrcoef(-TNdf['logL'],TNdf['SSE'])[0,1]))
plt.xlabel('-logL (TN)')
plt.ylabel('SSE (TN)')
plt.savefig('TN_logL_v_SSE_20samps.png')
plt.clf()